Repository kalkulacka-one/kalkulacka, pull requests merged in 2024-06, with the labels that each got.

#1 Fix typos in web
  apps/web/app/[lang]/zapojte-se/page.tsx
Labels: bug

#2 Add `FUNDING.yaml`
  .github/FUNDING.yml
Labels: documentation

#4 Add X link to web navigation
  apps/web/app/[lang]/layout.tsx
Labels: app:web
